sudo apt-get install supervisor

touch /var/www/html/jenga/shared/jenga-worker.log
sudo nano /etc/supervisor/conf.d/jenga-worker.conf

---------------------------------------------------------------------------------------------------------
[program:jenga-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/jenga/current/artisan queue:work redis --tries=3
autostart=true
autorestart=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/jenga/shared/jenga-worker.log
stopwaitsecs=30
---------------------------------------------------------------------------------------------------------
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start jenga-worker:*
sudo supervisorctl status​
---------------------------------------------------------------------------------------------------------
sudo supervisorctl stop all
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start all